# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Example' do
#  pod 'IFUIKit'
 pod 'IFUIKit', :path => '../'

 pod 'IFToast', :path => '../'
 pod 'IFTableView', :path => '../'
 pod 'IFHUD', :path => '../'
 pod 'IFEmptyView', :path => '../'
 pod 'IFAlert', :path => '../'

end
